### ISSUE TITLE
IMAP not working on several IOS 26.0 devices

### ISSUE THREAD

**Issue by pvnieuwkerk** [zone-eu/wildduck#869]
Hi,

We've setup our Wildduck running on release 1.45.13;
(through docker)
the webmail works, also on my android device through imap, no issues; on my macbook mail-app, no issues.

However, on multiple IOS devices, it just keeps spinning on 'Verifying'.
The log during this:
```
sill IMAP [wdfpjfk67z3yv75e] S: 1 OK CAPABILITY completed
sill IMAP [wdfpjfk67z3yv75e] C: 2 AUTHENTICATE PLAIN
sill IMAP [wdfpjfk67z3yv75e] S: +
sill IMAP [wdfpjfk67z3yv75e] C: <32 bytes of data>
info Gelf {"short_message":"WILDDUCK [AUTHOK] pvnieuwkerk","_mail_action":"auth","_auth_result":"success","_username":"pvnieuwkerk","_domain":"mydomain.com","_user":"68a2219a4772e91c30a82f27","_password_type":"master","_scope":"imap","_ip":"172.18.0.1","_sess":"wdfpjfk67z3yv75e","facility":"wildduck","host":"8f3dbb9fb4cf","timestamp":1757861279.399,"_component":"wildduck"}
info Gelf {"short_message":"WILDDUCK [CONNSTART] Connection established for 68a2219a4772e91c30a82f27","_connection":"establish","_service":"imap","_sess":"wdfpjfk67z3yv75e","_user":"68a2219a4772e91c30a82f27","_cid":"wdfpjfk67z3yv75e","_ip":"172.18.0.1","_limit":15,"facility":"wildduck","host":"8f3dbb9fb4cf","timestamp":1757861279.4,"_component":"wildduck"}
info IMAP [wdfpjfk67z3yv75e] pvnieuwkerk authenticated using PLAIN
sill IMAP [wdfpjfk67z3yv75e] New journal listener for 68a2219a4772e91c30a82f27 (pvnieuwkerk)
sill IMAP [wdfpjfk67z3yv75e] S: * CAPABILITY IMAP4rev1 APPENDLIMIT=26214400 CHILDREN CONDSTORE ENABLE ID IDLE MOVE NAMESPACE QUOTA SPECIAL-USE UIDPLUS UNSELECT UTF8=ACCEPT XLIST
sill IMAP [wdfpjfk67z3yv75e] S: 2 OK pvnieuwkerk authenticated
sill IMAP [wdfpjfk67z3yv75e] C: 3 CAPABILITY
sill IMAP [wdfpjfk67z3yv75e] S: * CAPABILITY IMAP4rev1 APPENDLIMIT=26214400 CHILDREN CONDSTORE ENABLE ID IDLE MOVE NAMESPACE QUOTA SPECIAL-USE UIDPLUS UNSELECT UTF8=ACCEPT XLIST
sill IMAP [wdfpjfk67z3yv75e] S: 3 OK CAPABILITY completed
sill IMAP [wdfpjfk67z3yv75e] C: 4 ID ("name" "iPhone Mail" "version" "23A340" "os" "iOS" "os-version" "26.0 (23A340)")
info IMAP [wdfpjfk67z3yv75e] Client identification data received
info IMAP [wdfpjfk67z3yv75e] name      : iPhone Mail
info IMAP [wdfpjfk67z3yv75e] version   : 23A340
info IMAP [wdfpjfk67z3yv75e] os        : iOS
info IMAP [wdfpjfk67z3yv75e] os-version: 26.0 (23A340)
info Gelf {"short_message":"WILDDUCK [CLIENT ID]","_mail_action":"client_id","_authenticated":"yes","_user":"68a2219a4772e91c30a82f27","_sess":"wdfpjfk67z3yv75e","_client_id_name":"iPhone Mail","_client_id_version":"23A340","_client_id_os":"iOS","_client_id_os-version":"26.0 (23A340)","facility":"wildduck","host":"8f3dbb9fb4cf","timestamp":1757861279.525,"_component":"wildduck"}
sill IMAP [wdfpjfk67z3yv75e] S: * ID ("name" "WildDuck IMAP Server" "version" "1.45.13" "vendor" "Kreata")
sill IMAP [wdfpjfk67z3yv75e] S: 4 OK ID completed
sill IMAP [wdfpjfk67z3yv75e] Removed journal listener from 68a2219a4772e91c30a82f27 (pvnieuwkerk)
info Gelf {"short_message":"WILDDUCK [CONNRELEASE] Connection released for 68a2219a4772e91c30a82f27","_connection":"release","_service":"imap","_sess":"wdfpjfk67z3yv75e","_user":"68a2219a4772e91c30a82f27","_cid":"wdfpjfk67z3yv75e","_ip":"172.18.0.1","facility":"wildduck","host":"8f3dbb9fb4cf","timestamp":1757861279.589,"_component":"wildduck"}
info IMAP [wdfpjfk67z3yv75e] Connection closed to [172.18.0.1]
info IMAP [mlmpen2lbdjckdwm] Connection closed to false
info IMAP [nmx2ynz3h6tan6k5] Connection closed to false
info IMAP [alkao333fi7wsgk4] Connection closed to false
info IMAP [lcskv7ipnt6ub5oj] Connection closed to false
info IMAP [663pzgqfjw3helpb] Connection closed to false
info IMAP [7oprpsufe26nxrew] Connection closed to false
info IMAP [42wsrnwsmcbiydbv] Connection closed to false
info IMAP [agy2pfm7yictdmru] Connection closed to false
info IMAP [mbzdfdpfxygm3yjh] Connection closed to false
info IMAP [ggzd3gcsohvxekj5] Connection closed to false
info IMAP [pwszttt657i24wqk] Connection closed to false
info IMAP [2guqt4wn3v5jnxob] Connection closed to false
info IMAP [ooqwsr4d7mjhs3pg] Connection closed to false
info IMAP [zqpqemixihfjclms] Connection closed to false
info IMAP [qtxwc4waioolu76z] Connection closed to false
info IMAP [iyijzn37wk6itfhi] Connection closed to false
info IMAP [y2nxrsq2md72h64x] Connection closed to false
info IMAP [zgguz3q6mym6a25h] Connection closed to false
info IMAP [tqlpjvehdgqxlmic] Connection closed to false
info IMAP [wg3l4dbuh5nv7wv2] Connection closed to false
info IMAP [3diecflbnu7ty5vh] Connection closed to false
info IMAP [bpaaqjn4haksjesz] Connection closed to false
info IMAP [lh3p2k46wd4cksdq] Connection closed to false
info IMAP [akf23x2jwqtdftkg] Connection closed to false
info IMAP [jeafqhgtlmtigfzx] Connection closed to false
info IMAP [r5lbohl2kqqraglt] Connection closed to false
sill IMAP [wrbhhownoe2nwdkb] C: <4 bytes of data>
sill IMAP [wrbhhownoe2nwdkb] S: 137 OK IDLE terminated
sill IMAP [wrbhhownoe2nwdkb] C: 138 noop
sill IMAP [wrbhhownoe2nwdkb] S: 138 OK Nothing done
sill IMAP [wrbhhownoe2nwdkb] C: 139 getquotaroot "INBOX"
sill IMAP [wrbhhownoe2nwdkb] Requested quota root info for "INBOX"
sill IMAP [wrbhhownoe2nwdkb] S: * QUOTAROOT "INBOX" ""
sill IMAP [wrbhhownoe2nwdkb] S: * QUOTA "" (STORAGE 20342 1048576)
sill IMAP [wrbhhownoe2nwdkb] S: 139 OK Success
sill IMAP [wrbhhownoe2nwdkb] C: 140 UID fetch 683:* (FLAGS)
sill IMAP [wrbhhownoe2nwdkb] FETCH: {"metadataOnly":true,"markAsSeen":false,"messages":1,"query":[{"query":"FLAGS","item":"flags","original":{"type":"ATOM","value":"FLAGS"}},{"query":"UID","item":"uid","original":{"type":"ATOM","value":"UID"}}],"changedSince":0,"isUid":true}
sill IMAP [wrbhhownoe2nwdkb] Requested FETCH for "68a2219a4772e91c30a82f28"
sill IMAP [wrbhhownoe2nwdkb] S: * 21 FETCH (FLAGS (\Seen) UID 682)
sill IMAP [wrbhhownoe2nwdkb] FETCHOK rows=1 user=68a2219a4772e91c30a82f27 mailbox=68a2219a4772e91c30a82f28 time=0.001
info Gelf {"short_message":"WILDDUCK [FETCH]","_mail_action":"fetch","_user":"68a2219a4772e91c30a82f27","_mailbox":"68a2219a4772e91c30a82f28","_sess":"wrbhhownoe2nwdkb","_mark_seen":"no","_is_uid":"yes","_message_count":1,"_query":"140 UID fetch 683:* (FLAGS)","_query_time":3,"_row_count":1,"_total_bytes":34,"_response":true,"facility":"wildduck","host":"8f3dbb9fb4cf","timestamp":1757861363.707,"_component":"wildduck"}
sill IMAP [wrbhhownoe2nwdkb] S: 140 OK UID FETCH completed
sill IMAP [wrbhhownoe2nwdkb] C: 141 IDLE
sill IMAP [wrbhhownoe2nwdkb] S: + idling
info IMAP [nxjh4yynap7t3mkp] Connection closed to false
info IMAP [5r74csa5npfn26am] Connection closed to false
info IMAP [tkwfwrordebrfl4j] Connection closed to false
info IMAP [d7othsj4mwflxltc] Connection closed to false
sill IMAP [4fc6rcpxchmbwtjf] C: 55.259 LIST "" "Notes/*"
sill IMAP [4fc6rcpxchmbwtjf] LIST for "Notes/*"
sill IMAP [4fc6rcpxchmbwtjf] S: 55.259 OK LIST completed
sill IMAP [4fc6rcpxchmbwtjf] C: 56.259 SELECT Notes (CONDSTORE)
sill IMAP [4fc6rcpxchmbwtjf] Opening "Notes"
sill IMAP [4fc6rcpxchmbwtjf] S: 56.259 NO [NONEXISTENT] SELECT completed
info IMAP [pq7rtzyj5dhmb2kr] Connection closed to false
info IMAP [fr56lhbjoxvculfn] Connection closed to false
info IMAP [2krdp7xmyclayhyl] Connection closed to false
info IMAP [iehlplhax5killa4] Connection closed to false
info IMAP [kuox3vcoueq4mny3] Connection closed to false
info IMAP [pe56ddzovvjngg4l] Connection closed to false
info IMAP [p4q7wdsf5c7ctnja] Connection closed to false
info IMAP [7yx3hxs3euu5gbuh] Connection closed to false
info IMAP [wyu7magwasd5iyzb] Connection closed to false
info IMAP [i4k3ixcmdipgioob] Connection closed to false
info IMAP [ui3qawx75lchv636] Connection closed to false
verb Tasks type=acme-update id=acme-update-id data={}
info IMAP [nb5rqtkbdtefp3sv] Connection closed to false
info IMAP [vi5cxl2jnfb6mh67] Connection closed to false
info IMAP [pr2tr6rt25xawet2] Connection closed to false
info IMAP [wsetamgoy7gyplwg] Connection closed to false
info IMAP [4q4vyswil7fypc2q] Connection closed to false
info IMAP [j4lczyni6rwpdcbb] Connection closed to false
info IMAP [f7jm2fsjlenjwumj] Connection closed to false
info IMAP [tbn7qsicyhs2qgq3] Connection closed to false
info IMAP [3xmgbc2pga34c23j] Connection closed to false
```

After a while it accepts it,
however, no mailboxes/folders are loading/showing in the ios-mail-client, and it just keeps spinning.

I'm not really sure how to debug/solve this.

I tried different accounts, different phones, account-password/app-password; 
and the ios profile. But all have the same result.

Anyone any clue?

**Comment by andris9** [comment]
This is normal with beta releases of iOS/macOS. There are lots of bugs and usually these get fixed by the actual release.

**Comment by pvnieuwkerk** [comment]
@andris9 It also happens with an iphone running IOS 18. 

```
info IMAP [zdgrvs4kzc6tqa5c] Client identification data received
info IMAP [zdgrvs4kzc6tqa5c] name      : iPhone Mail
info IMAP [zdgrvs4kzc6tqa5c] version   : 22G100
info IMAP [zdgrvs4kzc6tqa5c] os        : iOS
info IMAP [zdgrvs4kzc6tqa5c] os-version: 18.6.2 (22G100)
```

**Comment by andris9** [comment]
Well, strange, I have iOS18 and the mail app works just fine, maybe some kind of edge case 🤔

**Comment by NickOvt** [comment]
@pvnieuwkerk any updates?
Shall I close the issue or does the error persist still?

**Comment by hachre** [comment]
I'm currently evaluating a Wildduck stack setup and I've run into this same issue on iOS 26.4. I'm using the latest Wildduck 1.46.26 with the wildduck-dockerized stack. 

I've figured out what the issue was. In addition to the same log messages that were reported by the OP, when looking at the Traefik logs, I had messages in there such as this one:
```
traefik-1  | 2026-04-04T21:08:02Z ERR Error while handling TCP connection error="readfrom tcp 172.18.0.4:58088->172.18.0.6:143: tls: client requested unsupported application protocols (["imap"])"
```

The solution I found is to edit `dynamic_conf/dynamic.yml`:
In the original file there's a section like this near the top:
```
{{- if ne (env "TRAEFIK_TLS_MODE") "acme" }}
tls:
  certificates:
    - certFile: '{{ env "TRAEFIK_CERT_CONTAINER_FILE" }}'
      keyFile: '{{ env "TRAEFIK_KEY_CONTAINER_FILE" }}'
{{- end }}
```

I replaced this entire section with this:
```
{{- if ne (env "TRAEFIK_TLS_MODE") "acme" }}
tls:
  certificates:
    - certFile: '{{ env "TRAEFIK_CERT_CONTAINER_FILE" }}'
      keyFile: '{{ env "TRAEFIK_KEY_CONTAINER_FILE" }}'
  options:
    default:
      alpnProtocols:
        - h2
        - http/1.1
        - acme-tls/1
        - imap
{{- else }}
tls:
  options:
    default:
      alpnProtocols:
        - h2
        - http/1.1
        - acme-tls/1
        - imap
{{- end }}
```

This immediately brought the iOS Mail client to life. It may require a `docker compose restart traefik` otherwise. I don't know if this solution is optimal, but it works after this change.

**Comment by NickOvt** [comment]
@hachre That may be a good fix as it seems (I did a quick online search) that apple mail strictly advertises imap as the alpn and by default traefik does not accept it. I will fix the setting in wildduck-dockerized. 

Thank you!
Cheers
